version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile

    environment:
      # Only REACT_APP_ prefixed env variables are passed to the app.  See https://create-react-app.dev/docs/adding-custom-environment-variables/
      - REACT_APP_OPENAI_API_KEY=${OPENAPI_API_KEY_1}
      
    ports:
      - 8000:8000
      - 8080:8080
      - 3000:3000

    volumes:
      - ..:/workspace:cached      
    # network_mode: service:db
    command: sleep infinity

#   db:
#     image: postgres:latest
#     restart: unless-stopped
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_DB: postgres

# volumes:
#   postgres-data:
