version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile

    environment:
      # Only REACT_APP_ prefixed env variables are passed to the client-side app.  See https://create-react-app.dev/docs/adding-custom-environment-variables/
      - PROMPTMAN_OPENAI_API_KEY=${OPENAPI_API_KEY_1}
      - REACT_APP_PROMPTMAN_SERVICE_URL=http://localhost:8080
      
    ports:
      - 8000:8000
      - 8080:8080
      - 3000:3000

    volumes:
      - ..:/workspace:cached      
    # network_mode: service:db
    command: sleep infinity

